#!/bin/bash
set -x
URL="http://localhost:8080"
JSON="Content-Type: application/json"
JWT_REQ='{ "email": "'$1'", "password": "hunter2"}'
curl -s -d "$JWT_REQ" -X POST -H "$JSON" $URL/api/v1/create
JWT_RESP=$(curl -s -d "$JWT_REQ" -H "$JSON" $URL/api/v1/login)
AUTH_TOKEN=$(echo $JWT_RESP | python3 -c "import sys, json; print(json.load(sys.stdin)['authToken'])")
AUTH_HEADER="Authorization: Bearer "$AUTH_TOKEN
USER_RESP=$(curl -s -H "$AUTH_HEADER" $URL/api/v1/user)
RECOMMENDED_USERS=$(curl -s -H "$AUTH_HEADER" $URL/api/v1/recommends)
