#!/bin/bash
set -x
URL="http://localhost:8080"
JSON="Content-Type: application/json"
ACCOUNT=$(curl -s -d '{ "email": "foo", "password": "baz"}' -X POST -H "$JSON" $URL/api/v1/create)
USERNAME=$(echo $ACCOUNT | python3 -c "import sys, json; print(json.load(sys.stdin)['username'])")
JWT_REQ='{ "username": "'$USERNAME'", "password": "hunter2"}'
JWT_RESP=$(curl -s -d "$JWT_REQ" -H "$JSON" $URL/api/v1/login)
AUTH_TOKEN=$(echo $JWT_RESP | python3 -c "import sys, json; print(json.load(sys.stdin)['authToken'])")
AUTH_HEADER="Authorization: Bearer "$AUTH_TOKEN
USER_RESP=$(curl -s -H "$AUTH_HEADER" $URL/api/v1/user)
PUT_RESP=$(curl -s -d '{ "zipcode": "80210" }' -X PUT -H "$AUTH_HEADER" -H "$JSON" $URL/api/v1/user)
