#!/bin/bash
set -x
JSON_VALUE='{"entries":[{"bookId":"0"},{"bookId":"1"},{"bookId":"2"},{"bookId":"3"},{"bookId":"4"},{"bookId":"5"},{"bookId":"6"},{"bookId":"7"},{"bookId":"8"},{"bookId":"9"}]}'
URL="http://localhost:8080"
JSON="Content-Type: application/json"
RESP=$(curl -s -d "$JSON_VALUE" -X POST -H "$JSON" $URL/api/v1/pleasework)
